POST  http://localhost:3003/api/blogs
Content-Type: application/json

{
 "title" : "for second blog",
 "author" : "yayoo pol",
 "url" : "http://gghose.tcom",
 "likes" : 260,
 "userId" : "66df2bb913d3e9a58b27c5c1"
}